apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: twisted-infra-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: infra
  sourceRepos:
    - "*"
  destinations:
    - namespace: infra
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: media
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: storage
      server: https://kubernetes.default.svc
    - namespace: ingress
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
