apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-appbundle-app-yorkhaus-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namspace: "*"
      server: "*"

  project: appbundle-project-yorkhaus-infra
  sourceRepos:
    - "*"
