apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-yorkhaus-infra
  source:
    path: argocd/templates/
    repoURL: https://github.com/dysorkd/york-haus-cluster
    targetRevision: HEAD
