apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dsyorkd/yorkhaus-infra.git
        revision: HEAD
        directories:
          - path: app_base/observability/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/dsyorkd/yorkhaus-infra.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
